tasks:
  - init: sudo add-apt-repository --update -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -y && sudo apt-get -y --fix-broken install gcc-11 g++-11 && sudo apt-get install -y valgrind libjsoncpp-dev && cmake .